name: Build and Deploy Bank Application

on:
  push:
    branches:
      - main


jobs:
  build-deploy:
    name: Build and deploy Bank Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17

#      - name: Verify Java Version
#        run: java -version

#      - name: Unit Tests
#        run: mvn -B test --file pom.xml

      - name: Build the Application
        run:
          mvn clean
          mvn -B package --file pom.xml
